### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by TheOmegaPope** [petykowski/London-Underground-Dot-Matrix-Typeface#1]
Hi there, I am hoping you can talk me around where the breakdown is between your gorgeous font files and Microsoft. 

My computer insists ALL the font files are not valid no matter how I try to install them, preview them, or insert them into the folder.
I can see the XML looks right viewed in notepad++ but obviously it is upset with something. Do you have any insight on how to fix them?

![image](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/36393603/4a47b492-e425-4693-9895-b5423d87fe36)

Chris

**Comment by petykowski** [comment]
Hey @TheOmegaPope ! Thanks for the feedback, I hope you can use it very soon.

Let me try and replicate the issue on my Windows machine and let you know if I experience the same.

Any chance you can let me know what version of Windows you are running?

**Comment by TheOmegaPope** [comment]
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎2021-‎08-‎11
OS build	19045.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

and thank you

**Comment by petykowski** [comment]
@TheOmegaPope, thank you for the details. I can verify that my Windows computer is able to preview and install the font with no issues. I am running a very similar configuration:

```
Edition: Windows 10 Enterprise
Version: 21H2
Installed On: 28/03/2022
OS build: 19044.2965
Experience: Windows Feature Experience Pack 1000.19041.1000.0
```

I noticed two items in your original post.

1. The font file is currently sitting in a OneDrive; can you move the font to your local downloads or desktop and then try to open the font?
2. It looks like it might be a work laptop, 'Government of BC'; is it possible that there are enterprise restrictions that would prohibit use of a downloaded font?
