### ISSUE TITLE
Q is for Queensbury

### ISSUE THREAD

**Issue by robhagemans** [petykowski/London-Underground-Dot-Matrix-Typeface#2]
Hi, kudos for this project! For a long time I'd been sitting on the Tube idly staring at the displays and thinking one day I should recreate the bitmap font, but obviously never actually did! 

As I'm in NW London  I thought I was in a good position to help with the missing Q, K and F, and have some hope of one day spotting a U. I realise you said "contact me on Twitter", but I'm not on Twitter, so here goes. I'm attaching a small number of video stills that I played with for the letter Q - more than happy to share the original stills or the whole video clip, which is about 12 MiB. 

![Q00007-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/1fdc69c5-7979-452d-8afe-bb84b2890a78)
![Q00007-50](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/8d53b27e-2a9d-47cb-a869-bd6ced71ca26)
![Q00003-45](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/7dffc54b-223d-45e0-9a41-d67bde276112)
![Q00003-56](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/9031aef7-91d1-44df-9480-6fafd3e0a11e)
![Q00005-54](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/58be2bf9-6986-4033-8c6d-d770b6bbcaf7)

![Q00365-46](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/6a9a25c2-ea1a-407b-9135-c08f14bd416b) 
I'm a bit disappointed with the quality of the picture so may need to go back and take a close-up when I feel like it some quiet day. 

However what I think I can see is that the "leg" of the Q doesn't seem to extend to the inside of the "O", and instead extends below the baseline and to the right of the right bound of the "O" it appears to me they made the Q asymmetric so as to have an even gap either side of the leg. I read it like this:

    ...@@@@@@.....
    ..@@@@@@@@....
    .@@@....@@@...
    .@@......@@...
    @@........@@..
    @@........@@..
    @@........@@..
    @@........@@..
    @@........@@..
    .@@......@@@..
    .@@@....@@@...
    ..@@@@@@@@@@..
    ...@@@@@@.@@@.
    ...........@.. 
    ..............
    ..............

I also took a clip at Kingsbury which I'll open a separate ticket for once I've had a look. F for Finchley Road and hopefully a stray U (Underground?) to follow.

**Comment by robhagemans** [comment]
Much better stills, from https://www.youtube.com/watch?v=VdS9RxWD6is (around 4:36)

![Q-yt-00001-cropped](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/b8686f94-4f7d-4a75-8cef-bc232e5e15b6)
![Q-yt-00002-cropped](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/145aa9fb-d268-4952-8c42-ffbcf61b7f29)

**Comment by petykowski** [comment]
Updating Q to match above reference photos. Personally validated against the above YouTube video.

<img width="343" alt="image" src="https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/4651829/2b8b20f4-197a-4dc5-bcbd-1f4635748b3d">
