### ISSUE TITLE
K is for Kingsbury

### ISSUE THREAD

**Issue by robhagemans** [petykowski/London-Underground-Dot-Matrix-Typeface#3]
As in my post on Q, some (slightly disappointing) photos of the capital K from the Jubilee line at Kingsbury.

![K00007-49](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/e3cfd04c-22ed-4c08-941a-c70701b467ee)
![K00007-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/7190ada0-28a2-43c0-bf60-32803a420a35)
![K00019-47](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/a8e23ed7-6550-4627-b357-f5e9f4f0e66a)
![K00019-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/288cfaf2-b5d0-49f7-8f9f-1073b40157ec)
![K00024-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/69a77d76-5970-4d66-9c04-b5fc7e255163)
![K00027-48](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/c6cec244-7b6b-4f0f-be54-898c3be2def7)
![K00027-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/a6473f21-1577-4bde-bb8a-826e762631b1)

**Comment by robhagemans** [comment]
A much better still, from https://www.youtube.com/watch?v=VdS9RxWD6is (around 6:48).

![K-yt-00004-crop](https://github.com/petykowski/London-Underground-Dot-Matrix-Typeface/assets/7723154/84e95dec-b45b-46a2-a655-ed3060966ae8)

**Comment by petykowski** [comment]
Hey @robhagemans thank you so much for sharing these letters, it is incredibly helpful. A bit busy this past week, but I'll try and get them updated into the typeface next week.

I'll keep you updated on the progress.

**Comment by robhagemans** [comment]
No worries, my pleasure! 
I was wondering about the lowercase `j` as well - it's not io your list of 'best effort' letters, but I'm surprised it has no descender like the `g` (or a narrower variant)... I haven't seen a `j` on the Jubilee myself though, does this come from a picture?

**Comment by petykowski** [comment]
I have reviewed the above video and cross referenced with another video, [here](https://youtu.be/rEFIh3omybk). It looks like the `K` character is accurate I will remove it from the best effort list in the README file.

In regards to the `j` you may be on to something. It feels odd that it does not have a descender. I am going through my old reference material, if I cannot find my original source I will add it to the list of unverified characters.
